import { test } from 'node:test';
import assert from 'node:assert/strict';
import { renderDoc, RenderError, detectLang } from '../src/render.js';
import { ParseError } from '../src/parse.js';

const SRC = `---
title: 测试页
subtitle: 副标题
source: example.org
---
导语 **加粗**。

## A 表格 {span=2 meta="Section 3"}
| 形式 | 状态 |
|---|---|
| 命令式 | ok 已批准 |
| 进行时 | no |

## 原始块
\`\`\`html
<div class="raw-x">raw</div>
\`\`\`
\`\`\`python
print("<x>")
\`\`\`
`;

test('render: 产出完整单文件 HTML，带主题属性与 viewport', () => {
  const { html, meta } = renderDoc(SRC);
  assert.match(html, /^<!doctype html>/);
  assert.match(html, /<html lang="zh-CN" data-theme="blueprint" data-mode="auto">/);
  assert.match(html, /name="viewport"/);
  assert.equal(meta.template, 'sheet');
});

test('render: 零外部依赖——无 http(s) 引用的脚本、样式、字体', () => {
  const { html } = renderDoc(SRC);
  assert.doesNotMatch(html, /<script[^>]+src=/);
  assert.doesNotMatch(html, /<link[^>]+href=/);
  assert.doesNotMatch(html, /@import|url\(\s*['"]?https?:/);
});

test('render: 面板 ID、标题、meta、span 生效', () => {
  const { html } = renderDoc(SRC);
  assert.match(html, /id="panel-A" style="grid-column: span 2"/);
  assert.match(html, /<span class="am-panel-meta">Section 3<\/span>/);
  assert.match(html, /<h2>原始块<\/h2>/);
});

test('render: 页头含标题、副标题、额外 meta、导语', () => {
  const { html } = renderDoc(SRC);
  assert.match(html, /<h1>测试页<\/h1>/);
  assert.match(html, /am-sub">副标题/);
  assert.match(html, /<b>source<\/b>example.org/);
  assert.match(html, /<strong>加粗<\/strong>/);
});

test('render: 表格状态词渲染为徽章', () => {
  const { html } = renderDoc(SRC);
  assert.match(html, /am-status--ok"><span class="am-status-icon" aria-hidden="true">✓<\/span>已批准/);
  assert.match(html, /am-status--no/);
  assert.match(html, /am-table-wrap/);
});

test('render: html/svg fence는 원본 마크업으로 삽입하고 알 수 없는 언어만 코드로 escape', () => {
  const { html } = renderDoc(SRC);
  assert.match(html, /<div class="raw-x">raw<\/div>/);
  assert.match(html, /<pre class="am-code"><code data-lang="python">print\(&quot;&lt;x&gt;&quot;\)<\/code><\/pre>/);
});

test('render: Markdown raw HTML과 javascript 링크를 유지해 인터랙션을 허용', () => {
  const { html } = renderDoc('## A\n<button onclick="this.textContent=\'ok\'">go</button>\n[x](javascript:void(0))');
  assert.match(html, /<button onclick="this\.textContent='ok'">go<\/button>/);
  assert.match(html, /href="javascript:void\(0\)"/);
});

test('render: CSP는 inline interaction을 허용하고 외부 통신은 제한하며 HTTPS font를 허용', () => {
  const { html } = renderDoc('## A\nx');
  assert.match(html, /default-src 'none'/);
  assert.match(html, /script-src 'unsafe-inline'/);
  assert.match(html, /style-src 'unsafe-inline'/);
  assert.match(html, /connect-src 'none'/);
  assert.match(html, /font-src https: data:/);
  assert.match(html, /object-src 'none'/);
  assert.match(html, /frame-src 'none'/);
  assert.match(html, /form-action 'none'/);
  assert.match(html, /base-uri 'none'/);
  assert.match(html, /name="referrer" content="no-referrer"/);
});

test('render: 源稿转义后内嵌在隐藏 textarea 中，可原样取回', () => {
  const src = '## A\n```html\n<script>x</script></textarea>\n```';
  const { html } = renderDoc(src);
  const embedded = html.match(/<textarea id="am-source" hidden readonly aria-hidden="true">([\s\S]*?)<\/textarea>/)[1];
  assert.doesNotMatch(embedded, /<\/?(script|textarea)/);
  const unescaped = embedded.replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&amp;/g, '&');
  assert.equal(unescaped, src);
});

test('render: 页脚 colophon 含版本与生成时间', () => {
  assert.match(renderDoc('## A\nx').html, /<footer class="am-colophon">Generated by Answer me with HTML \d+\.\d+\.\d+ · \d{4}-\d{2}-\d{2} \d{2}:\d{2}<\/footer>/);
});

test('render: CLI 覆盖项生效并校验', () => {
  const { html } = renderDoc(SRC, { theme: 'shadcn', template: 'doc' });
  assert.match(html, /data-theme="shadcn"/);
  assert.match(html, /class="am-doc"/);
  assert.throws(() => renderDoc(SRC, { theme: 'x' }), ParseError);
});

test('render: doc 模板在 ≥3 面板时生成目录', () => {
  const { html } = renderDoc('---\ntemplate: doc\n---\n## 一\na\n## 二\nb\n## 三\nc');
  assert.match(html, /<nav class="am-toc"/);
  assert.match(html, /href="#panel-C">C · 三/);
});

test('render: 英文稿件使用英文界面文案', () => {
  const { html } = renderDoc('# Hello world\n## A Overview\nThis is a plain English page about things.');
  assert.match(html, /<html lang="en"/);
  assert.match(html, /Copy source/);
});

test('render: 한국어 원고는 한국어 UI와 lang=ko를 사용', () => {
  const { html } = renderDoc('# 인증 흐름\n## A 개요\n사용자 요청을 검증하고 토큰을 발급합니다.');
  assert.match(html, /<html lang="ko"/);
  assert.match(html, />테마: 도면<\/button>/);
  assert.match(html, />명암: 시스템 설정<\/button>/);
  assert.match(html, />원고 복사<\/button>/);
  assert.doesNotMatch(html, /主题：|明暗：|复制源稿/);
});

test('detectLang: 한국어/중국어/영어를 구분', () => {
  assert.equal(detectLang('한국어 기술 문서를 설명합니다.'), 'ko');
  assert.equal(detectLang('全中文内容'), 'zh');
  assert.equal(detectLang('all english words here'), 'en');
});

test('render: 统计面板与组件数量', () => {
  const { stats } = renderDoc(SRC);
  assert.equal(stats.panels, 2);
});

test('RenderError 类型存在', () => {
  assert.equal(new RenderError('x', { line: 3 }).line, 3);
});

test('render: rows 属性纵向跨行；bare 属性去掉面板标题栏', () => {
  const { html } = renderDoc('## A 高面板 {rows=2 span=2}\nx\n## B {bare}\ny');
  assert.match(html, /id="panel-A" style="grid-column: span 2; grid-row: span 2"/);
  assert.match(html, /<section class="am-panel am-panel--bare" id="panel-B">\n<div class="am-panel-body">/);
});

test('sheet: 面板放不下下一个时自动拉满当前行，不留空洞', async () => {
  const { fillRows } = await import('../src/templates/sheet.js');
  const P = (span) => ({ attrs: span ? { span } : {} });
  // cols=2：A(2) | B(1) C(2) → B 后面放不下 C，B 拉到 2
  assert.deepEqual(fillRows([P(2), P(), P(2), P()], 2), [2, 2, 2, 2]);
  // cols=3：A(1) B(1) C(2) → A B 占 2，C 放不下，B 拉到 2；C(2) 是最后一行，拉满到 3
  assert.deepEqual(fillRows([P(), P(), P(2)], 3), [1, 2, 3]);
  // 刚好填满时不变
  assert.deepEqual(fillRows([P(), P(2), P(3)], 3), [1, 2, 3]);
  // 用了 rows 跨行时不做调整，保留作者的布局
  assert.deepEqual(fillRows([{ attrs: { rows: 2 } }, P(), P(2)], 3), [1, 1, 2]);
});

test('sheet: 自动拉宽体现在渲染结果里', () => {
  const { html } = renderDoc('---\ncols: 2\n---\n## A {span=2}\nx\n## B\ny\n## C {span=2}\nz');
  assert.match(html, /id="panel-B" style="grid-column: span 2"/);
});
